services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Nowo\SelectAllChoiceBundle\Twig\NowoSelectAllChoiceTwigExtension:
    tags: [twig.extension]

  Nowo\SelectAllChoiceBundle\Form\Extension\ChoiceTypeSelectAllExtension:
    arguments:
      $defaultLabel: '%nowo_select_all_choice.default_label%'
      $defaultPosition: '%nowo_select_all_choice.default_position%'
      $defaultToggleCssClass: '%nowo_select_all_choice.default_toggle_css_class%'
      $defaultWrapperCssClass: '%nowo_select_all_choice.default_wrapper_css_class%'
      $defaultLabelCssClass: '%nowo_select_all_choice.default_label_css_class%'
      $defaultContainerCssClass: '%nowo_select_all_choice.default_container_css_class%'
      $translationDomain: '%nowo_select_all_choice.translation_domain%'
      $debug: '%nowo_select_all_choice.debug%'
